#!/usr/bin/env bash

# original dmenu_run
# dmenu_path | dmenu "$@" | ${SHELL:-"/bin/sh"} &

# alternative dmenu_run with history

CACHEDIR=${XDG_CACHE_HOME:-$HOME/.cache}

if [[ -d $CACHEDIR ]]; then
    CACHE=$CACHEDIR/dmenu_run
    HIST=$CACHEDIR/dmenu_history
else
    # if no xdg dir, fall back to dotfiles in ~
    CACHE=$HOME/.dmenu_cache
    HIST=$HOME/.dmenu_history
fi

IFS=:
stest -dqr -n "$CACHE" $PATH && stest -flx $PATH | sort -u > "$CACHE"
unset IFS

awk -v histfile=$HIST 'BEGIN {
while( (getline < histfile) > 0 ) {
    sub("^[0-9]+\t","")
    print
    x[$0]=1
}
} !x[$0]++ ' "$CACHE" | dmenu "$@" | awk -v histfile=$HIST 'BEGIN {
FS=OFS="\t"
while ( (getline < histfile) > 0 ) {
    count=$1
    sub("^[0-9]+\t","")
    fname=$0
    history[fname]=count
}
close(histfile)
}

{
    history[$0]++
    print
}

END {
if(!NR) exit
    for (f in history)
        print history[f],f | "sort -t '\t' -k1rn >" histfile
    }' | ${SHELL:-/bin/sh} &
